version: '3.4'

services:
  main_mq:
    container_name: rabbitMQ
    image: rabbitmq:management
    hostname: rabbitMQHost
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - main_rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
     - microservice-network

volumes:
  main_rabbitmq_data: 

networks:
  microservice-network:
    external: true