version: '3.8'

services:
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - microservice-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  microservice-network:
    external: true